Search.appendIndex(
    [
                {
            "fqsen": "\\chillerlan\\Settings\\Attributes\\ThrowOnInvalidProperty",
            "name": "ThrowOnInvalidProperty",
            "summary": "Tells\u0020the\u0020magic\u0020get\/set\u0020methods\u0020whether\u0020to\u0020throw\u0020when\u0020a\u0020properety\u0020is\u0020inaccessible",
            "url": "classes/chillerlan-Settings-Attributes-ThrowOnInvalidProperty.html"
        },                {
            "fqsen": "\\chillerlan\\Settings\\Attributes\\ThrowOnInvalidProperty\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/chillerlan-Settings-Attributes-ThrowOnInvalidProperty.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\Settings\\Attributes\\ThrowOnInvalidProperty\u003A\u003A\u0024throwOnInvalid",
            "name": "throwOnInvalid",
            "summary": "",
            "url": "classes/chillerlan-Settings-Attributes-ThrowOnInvalidProperty.html#property_throwOnInvalid"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract",
            "name": "SettingsContainerAbstract",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "SettingsContainerAbstract\u0020constructor.",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003Aconstruct\u0028\u0029",
            "name": "construct",
            "summary": "calls\u0020a\u0020method\u0020with\u0020trait\u0020name\u0020as\u0020replacement\u0020constructor\u0020for\u0020each\u0020used\u0020trait\n\u0028remember\u0020pre\u002Dphp5\u0020classname\u0020constructors\u003F\u0020yeah,\u0020basically\u0020this.\u0029",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_construct"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Retrieve\u0020the\u0020value\u0020of\u0020\u0024property",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___get"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Set\u0020\u0024property\u0020to\u0020\u0024value\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___set"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "Checks\u0020if\u0020\u0024property\u0020is\u0020set\u0020\u0028aka.\u0020not\u0020null\u0029,\u0020excluding\u0020private\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___isset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__unset\u0028\u0029",
            "name": "__unset",
            "summary": "Unsets\u0020\u0024property\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___unset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___toString"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020an\u0020array\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_toArray"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AfromIterable\u0028\u0029",
            "name": "fromIterable",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020iterable",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_fromIterable"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AtoJSON\u0028\u0029",
            "name": "toJSON",
            "summary": "Returns\u0020a\u0020JSON\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_toJSON"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AfromJSON\u0028\u0029",
            "name": "fromJSON",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020JSON\u0020string",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_fromJSON"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_jsonSerialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Returns\u0020a\u0020serialized\u0020string\u0020representation\u0020of\u0020the\u0020object\u0020in\u0020its\u0020current\u0020state\u0020\u0028except\u0020static\/readonly\u0020properties\u0029",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_serialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "Restores\u0020the\u0020data\u0020\u0028except\u0020static\/readonly\u0020properties\u0029\u0020from\u0020the\u0020given\u0020serialized\u0020object\u0020to\u0020the\u0020current\u0020instance",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_unserialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "Returns\u0020a\u0020serialized\u0020array\u0020representation\u0020of\u0020the\u0020object\u0020in\u0020its\u0020current\u0020state\u0020\u0028except\u0020static\/readonly\u0020properties\u0029,\nbypassing\u0020custom\u0020getters\u0020and\u0020property\u0020hooks",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___serialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__unserialize\u0028\u0029",
            "name": "__unserialize",
            "summary": "Restores\u0020the\u0020data\u0020from\u0020the\u0020given\u0020array\u0020to\u0020the\u0020current\u0020instance,\nbypassing\u0020custom\u0020setters\u0020and\u0020property\u0020hooks",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___unserialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003ASET_PREFIX",
            "name": "SET_PREFIX",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#constant_SET_PREFIX"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AGET_PREFIX",
            "name": "GET_PREFIX",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#constant_GET_PREFIX"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface",
            "name": "SettingsContainerInterface",
            "summary": "a\u0020generic\u0020container\u0020with\u0020magic\u0020getter\u0020and\u0020setter",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Retrieve\u0020the\u0020value\u0020of\u0020\u0024property",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___get"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Set\u0020\u0024property\u0020to\u0020\u0024value\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___set"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "Checks\u0020if\u0020\u0024property\u0020is\u0020set\u0020\u0028aka.\u0020not\u0020null\u0029,\u0020excluding\u0020private\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___isset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__unset\u0028\u0029",
            "name": "__unset",
            "summary": "Unsets\u0020\u0024property\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___unset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___toString"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020an\u0020array\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_toArray"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AfromIterable\u0028\u0029",
            "name": "fromIterable",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020iterable",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_fromIterable"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AtoJSON\u0028\u0029",
            "name": "toJSON",
            "summary": "Returns\u0020a\u0020JSON\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_toJSON"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AfromJSON\u0028\u0029",
            "name": "fromJSON",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020JSON\u0020string",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_fromJSON"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest",
            "name": "ContainerTest",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003Aconstruct\u0028\u0029",
            "name": "construct",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_construct"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_get"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_set"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_toArray"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtoJSON\u0028\u0029",
            "name": "toJSON",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_toJSON"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AfromJsonException\u0028\u0029",
            "name": "fromJsonException",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_fromJsonException"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AfromJsonTypeError\u0028\u0029",
            "name": "fromJsonTypeError",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_fromJsonTypeError"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003Aserializable\u0028\u0029",
            "name": "serializable",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_serializable"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AunserializeInvalidDataException\u0028\u0029",
            "name": "unserializeInvalidDataException",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_unserializeInvalidDataException"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AunserializeInvalidObjectException\u0028\u0029",
            "name": "unserializeInvalidObjectException",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_unserializeInvalidObjectException"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AthrowOnInaccessibleGet\u0028\u0029",
            "name": "throwOnInaccessibleGet",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_throwOnInaccessibleGet"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AthrowOnInaccessibleSet\u0028\u0029",
            "name": "throwOnInaccessibleSet",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_throwOnInaccessibleSet"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ExceptionTestContainer",
            "name": "ExceptionTestContainer",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ExceptionTestContainer.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ExceptionTestContainer\u003A\u003A\u0024accessible",
            "name": "accessible",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ExceptionTestContainer.html#property_accessible"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ExceptionTestContainer\u003A\u003A\u0024inaccessible",
            "name": "inaccessible",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ExceptionTestContainer.html#property_inaccessible"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer",
            "name": "PropertyHooksContainer",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer\u003A\u003Aset_test1\u0028\u0029",
            "name": "set_test1",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html#method_set_test1"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer\u003A\u003Aset_test4\u0028\u0029",
            "name": "set_test4",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html#method_set_test4"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer\u003A\u003Aget_test4\u0028\u0029",
            "name": "get_test4",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html#method_get_test4"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer\u003A\u003A\u0024test1",
            "name": "test1",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html#property_test1"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer\u003A\u003A\u0024test2",
            "name": "test2",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html#property_test2"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer\u003A\u003A\u0024test3",
            "name": "test3",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html#property_test3"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksContainer\u003A\u003A\u0024test4",
            "name": "test4",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksContainer.html#property_test4"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksTest",
            "name": "PropertyHooksTest",
            "summary": "Tests\u0020to\u0020ensure\u0020that\u0020properties\u0020with\u0020hooks\u0020\u0028PHP\u00208.4\u002B\u0029\u0020produce\u0020the\u0020same\u0020results\u0020as\u0020the\u0020custom\u0020get\/set\u0020methods",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksTest.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksTest\u003A\u003ApropertyHooks\u0028\u0029",
            "name": "propertyHooks",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksTest.html#method_propertyHooks"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksTest\u003A\u003Aserializable\u0028\u0029",
            "name": "serializable",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksTest.html#method_serializable"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\PropertyHooksTest\u003A\u003AtoJSON\u0028\u0029",
            "name": "toJSON",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-PropertyHooksTest.html#method_toJSON"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestContainer",
            "name": "TestContainer",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestContainer.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestContainer\u003A\u003A\u0024test3",
            "name": "test3",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestContainer.html#property_test3"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait",
            "name": "TestOptionsTrait",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003ATestOptionsTrait\u0028\u0029",
            "name": "TestOptionsTrait",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#method_TestOptionsTrait"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003Aset_test5\u0028\u0029",
            "name": "set_test5",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#method_set_test5"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003Aget_test6\u0028\u0029",
            "name": "get_test6",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#method_get_test6"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test1",
            "name": "test1",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test1"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test2",
            "name": "test2",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test2"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024testConstruct",
            "name": "testConstruct",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_testConstruct"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test4",
            "name": "test4",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test4"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test5",
            "name": "test5",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test5"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test6",
            "name": "test6",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test6"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\chillerlan\\Settings\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/chillerlan-settings-attributes.html"
        },                {
            "fqsen": "\\chillerlan\\Settings",
            "name": "Settings",
            "summary": "",
            "url": "namespaces/chillerlan-settings.html"
        },                {
            "fqsen": "\\chillerlan",
            "name": "chillerlan",
            "summary": "",
            "url": "namespaces/chillerlan.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest",
            "name": "SettingsTest",
            "summary": "",
            "url": "namespaces/chillerlan-settingstest.html"
        }            ]
);
