Search.appendIndex(
    [
                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract",
            "name": "SettingsContainerAbstract",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "SettingsContainerAbstract\u0020constructor.",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___construct"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003Aconstruct\u0028\u0029",
            "name": "construct",
            "summary": "calls\u0020a\u0020method\u0020with\u0020trait\u0020name\u0020as\u0020replacement\u0020constructor\u0020for\u0020each\u0020used\u0020trait\n\u0028remember\u0020pre\u002Dphp5\u0020classname\u0020constructors\u003F\u0020yeah,\u0020basically\u0020this.\u0029",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_construct"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Retrieve\u0020the\u0020value\u0020of\u0020\u0024property",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___get"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Set\u0020\u0024property\u0020to\u0020\u0024value\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___set"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "Checks\u0020if\u0020\u0024property\u0020is\u0020set\u0020\u0028aka.\u0020not\u0020null\u0029,\u0020excluding\u0020private\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___isset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__unset\u0028\u0029",
            "name": "__unset",
            "summary": "Unsets\u0020\u0024property\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___unset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___toString"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020an\u0020array\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_toArray"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AfromIterable\u0028\u0029",
            "name": "fromIterable",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020iterable",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_fromIterable"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AtoJSON\u0028\u0029",
            "name": "toJSON",
            "summary": "Returns\u0020a\u0020JSON\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_toJSON"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AfromJSON\u0028\u0029",
            "name": "fromJSON",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020JSON\u0020string",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_fromJSON"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_jsonSerialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Returns\u0020a\u0020serialized\u0020string\u0020representation\u0020of\u0020the\u0020object\u0020in\u0020its\u0020current\u0020state\u0020\u0028except\u0020static\/readonly\u0020properties\u0029",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_serialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "Restores\u0020the\u0020data\u0020\u0028except\u0020static\/readonly\u0020properties\u0029\u0020from\u0020the\u0020given\u0020serialized\u0020object\u0020to\u0020the\u0020current\u0020instance",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method_unserialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "Returns\u0020a\u0020serialized\u0020string\u0020representation\u0020of\u0020the\u0020object\u0020in\u0020its\u0020current\u0020state\u0020\u0028except\u0020static\/readonly\u0020properties\u0029",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___serialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003A__unserialize\u0028\u0029",
            "name": "__unserialize",
            "summary": "Restores\u0020the\u0020data\u0020from\u0020the\u0020given\u0020array\u0020to\u0020the\u0020current\u0020instance",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#method___unserialize"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003ASET_PREFIX",
            "name": "SET_PREFIX",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#constant_SET_PREFIX"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerAbstract\u003A\u003AGET_PREFIX",
            "name": "GET_PREFIX",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerAbstract.html#constant_GET_PREFIX"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface",
            "name": "SettingsContainerInterface",
            "summary": "a\u0020generic\u0020container\u0020with\u0020magic\u0020getter\u0020and\u0020setter",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Retrieve\u0020the\u0020value\u0020of\u0020\u0024property",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___get"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Set\u0020\u0024property\u0020to\u0020\u0024value\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___set"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "Checks\u0020if\u0020\u0024property\u0020is\u0020set\u0020\u0028aka.\u0020not\u0020null\u0029,\u0020excluding\u0020private\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___isset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__unset\u0028\u0029",
            "name": "__unset",
            "summary": "Unsets\u0020\u0024property\u0020while\u0020avoiding\u0020private\u0020and\u0020non\u002Dexisting\u0020properties",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___unset"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method___toString"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020an\u0020array\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_toArray"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AfromIterable\u0028\u0029",
            "name": "fromIterable",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020iterable",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_fromIterable"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AtoJSON\u0028\u0029",
            "name": "toJSON",
            "summary": "Returns\u0020a\u0020JSON\u0020representation\u0020of\u0020the\u0020settings\u0020object",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_toJSON"
        },                {
            "fqsen": "\\chillerlan\\Settings\\SettingsContainerInterface\u003A\u003AfromJSON\u0028\u0029",
            "name": "fromJSON",
            "summary": "Sets\u0020properties\u0020from\u0020a\u0020given\u0020JSON\u0020string",
            "url": "classes/chillerlan-Settings-SettingsContainerInterface.html#method_fromJSON"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest",
            "name": "ContainerTest",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestConstruct\u0028\u0029",
            "name": "testConstruct",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testConstruct"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestGet\u0028\u0029",
            "name": "testGet",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testGet"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestSet\u0028\u0029",
            "name": "testSet",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testSet"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestToArray\u0028\u0029",
            "name": "testToArray",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testToArray"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestToJSON\u0028\u0029",
            "name": "testToJSON",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testToJSON"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestFromJsonException\u0028\u0029",
            "name": "testFromJsonException",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testFromJsonException"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestFromJsonTypeError\u0028\u0029",
            "name": "testFromJsonTypeError",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testFromJsonTypeError"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestSerializable\u0028\u0029",
            "name": "testSerializable",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testSerializable"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestUnserializeInvalidDataException\u0028\u0029",
            "name": "testUnserializeInvalidDataException",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testUnserializeInvalidDataException"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\ContainerTest\u003A\u003AtestUnserializeInvalidObjectException\u0028\u0029",
            "name": "testUnserializeInvalidObjectException",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-ContainerTest.html#method_testUnserializeInvalidObjectException"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestContainer",
            "name": "TestContainer",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestContainer.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestContainer\u003A\u003A\u0024test3",
            "name": "test3",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestContainer.html#property_test3"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait",
            "name": "TestOptionsTrait",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003ATestOptionsTrait\u0028\u0029",
            "name": "TestOptionsTrait",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#method_TestOptionsTrait"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003Aset_test5\u0028\u0029",
            "name": "set_test5",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#method_set_test5"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003Aget_test6\u0028\u0029",
            "name": "get_test6",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#method_get_test6"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test1",
            "name": "test1",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test1"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test2",
            "name": "test2",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test2"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024testConstruct",
            "name": "testConstruct",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_testConstruct"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test4",
            "name": "test4",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test4"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test5",
            "name": "test5",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test5"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest\\TestOptionsTrait\u003A\u003A\u0024test6",
            "name": "test6",
            "summary": "",
            "url": "classes/chillerlan-SettingsTest-TestOptionsTrait.html#property_test6"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\chillerlan\\Settings",
            "name": "Settings",
            "summary": "",
            "url": "namespaces/chillerlan-settings.html"
        },                {
            "fqsen": "\\chillerlan",
            "name": "chillerlan",
            "summary": "",
            "url": "namespaces/chillerlan.html"
        },                {
            "fqsen": "\\chillerlan\\SettingsTest",
            "name": "SettingsTest",
            "summary": "",
            "url": "namespaces/chillerlan-settingstest.html"
        }            ]
);
