language: php

matrix:
  include:
    - php: 7.4

before_install:
  - pecl channel-update pecl.php.net
  - pecl install ast

install:
  - composer install --no-interaction --prefer-source
  - composer validate

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml
  - vendor/bin/phan

after_script: bash <(curl -s https://codecov.io/bash)
