language: php

matrix:
  include:
  - php: 7.2
  - php: 7.3
  - php: 7.4snapshot
  - php: nightly
  allow_failures:
  - php: 7.4snapshot
  - php: nightly


before_script: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_script: bash <(curl -s https://codecov.io/bash)
